import Link from "next/link";

export const metadata = {
    title: "thefourtheye's Single Page Apps",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body style={{ margin: "auto", maxWidth: 1024 }}>
                <div>
                    <nav
                        style={{
                            display: "flex",
                            justifyContent: "space-between",
                            alignItems: "center",
                            padding: "1rem",
                        }}
                    >
                        <Link href="/">SPA Home</Link>
                        <Link href="http://thefourtheye.in">Blog Home</Link>
                    </nav>
                </div>
                {children}
            </body>
        </html>
    );
}
